# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=225)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('fund_status', models.CharField(max_length=225)),
                ('current_valuation', models.IntegerField(max_length=225)),
                ('shares_available', models.IntegerField(default=1000000)),
                ('rental_income', models.DecimalField(decimal_places=10, max_digits=19)),
                ('capital_growth', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
