# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-24 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='investment_case',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_valuation',
            field=models.IntegerField(),
        ),
    ]
