# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='investment_case',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
