# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_investment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surveyor', models.CharField(max_length=225)),
                ('solicitor', models.CharField(max_length=225)),
                ('value', models.IntegerField()),
                ('status', models.CharField(default='active', max_length=25)),
                ('notes', models.TextField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Listing')),
            ],
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(default='active', max_length=25),
        ),
    ]
