# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20170420_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valuation',
            old_name='notes',
            new_name='valuation_brief',
        ),
    ]
