# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20170420_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_valuation',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='rental_income',
        ),
    ]
