# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20170420_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='capital_growth',
        ),
        migrations.AddField(
            model_name='valuation',
            name='capital_growth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
