# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20170420_1823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Financials',
            new_name='Financial',
        ),
    ]
