# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_investment_investor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='amount',
            new_name='investment_cost',
        ),
        migrations.AddField(
            model_name='investment',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='transaction_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
            preserve_default=False,
        ),
    ]
