# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20170515_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuation',
            name='status',
            field=models.CharField(default='current', max_length=25),
        ),
    ]
