# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-21 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_statement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statement',
            new_name='Wallet',
        ),
    ]
