# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20170521_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_name', models.CharField(max_length=50)),
                ('account_number', models.IntegerField()),
                ('sort_code', models.IntegerField()),
            ],
        ),
    ]
