# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_bankaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
