# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_delete_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
