# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20170602_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='investor',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
