# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_auto_20170602_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='floor_plan',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='images/lagopoly'),
        ),
    ]
