# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_listing_floor_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slide_images',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='images/lagopoly'),
        ),
    ]
