# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-10 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_listing_slide_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slide_images', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='images/lagopoly')),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='slide_images',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Listing'),
        ),
    ]
