# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_listingimage_ordering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='slide_images',
            new_name='slide_image',
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='ordering',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0),
        ),
    ]
