# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_auto_20170611_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investment_cost',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='investment',
            name='total_cost',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='investment',
            name='transaction_cost',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='investment',
            name='unit_price',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
