# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_listing_floor_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=225)),
                ('overview', models.TextField()),
                ('report_type', models.CharField(max_length=225)),
                ('doc', models.FileField(default='documents/no-file.pdf', max_length=225, upload_to='documents')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.Listing')),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='listing',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
