# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='documents/lagopoly/%Y%m%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='visiblity',
            field=models.BooleanField(default=False),
        ),
    ]
