# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-25 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20170525_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visiblity',
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
