# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='debit',
        ),
        migrations.AddField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='transaction',
            field=models.CharField(default='', max_length=6),
        ),
    ]
